### ISSUE TITLE
Adicionar Autores

### ISSUE THREAD

**Issue by dougs007** [cpa-bayarea/Prontuario-2.0#1]
Adicionar o nome de todos os autores, tal como informações necessárias.
Segue link para visualização da documentação atual =>
https://github.com/cpa-bayarea/Prontuario-2.0/blob/master/docs/Autores.md

**Comment by dougs007** [comment]
@jaolima @resplandeluiz, @Renanis00, @Victorsouza2382 as informações de vocês estão certas ? Caso não estejam, me mandem no grupo do whats e me marquem por favor.

**Comment by Renanis00** [comment]
@dougs007 alterei o documento mas não tenho certeza se foi sucedido.
