### ISSUE TITLE
Pontos de Atenção

### ISSUE THREAD

**Issue by orionteles** [cpa-bayarea/Prontuario-2.0#27]
Adicionar Datatables
Adicionar Máscaras
	Telefones
	CPF	
Atentar ao tamanho máximo dos campos
Atentar aos campos obrigatórios
	Colocar * nos labels obrigatórios
	Colocar required nos labels obrigatórios

No cadastro de Grupo Item, o campo "Outro" está obrigatório
Adicionar SweetAlert ao tentar excluir os registros
Adicionar Chosen Select

**Comment by dougs007** [comment]
Finalizado pois já foi atendido boa parte do que foi citado.
