### ISSUE TITLE
Padronizando o projeto

### ISSUE THREAD

**Issue by jaolima** [cpa-bayarea/Prontuario-2.0#35]
- [x] Definir tela inicial(home) como o agendamento 
- [x] padronizar todos os botões em todas as tabelas do projeto

**Comment by dougs007** [comment]
@jaolima Acho que deve ser feito um modelo a ser seguido antes de começarem a tocar a demanda, o que acha?

**Comment by dougs007** [comment]
Fechando a demanda pois o 1 item já foi resolvido e o segundo estou lançando uma nova feature na branch dev-douglas
