### ISSUE TITLE
Ajustes no formulário de TRIAGEM 

### ISSUE THREAD

**Issue by jaolima** [cpa-bayarea/Prontuario-2.0#60]
-[X] Tirar a mascara do RG 
-[X] Tirar o label idade e colocar a data de nascimento 
-[] Acrescentar o date picker no campo de data 
-[X] Mudar o label de aluno para terapeuta
-[X] Campos sem sentido 
-[X] Marcar os campos obrigtorios com o asterisco 
-[X] Campos não aparecendo 
-[X] Ao salvar ha um erro na coluna TX_NOME

**Comment by dougs007** [comment]
Branch: feature-douglas
